# Generated by Django 4.1.1 on 2022-10-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255, null=True)),
                ('budget', models.IntegerField()),
                ('status', models.CharField(choices=[('0', 'Active'), ('1', 'Paused'), ('2', 'Completed')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
            },
        ),
    ]
