# Generated by Django 4.1.1 on 2022-10-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('0', 'Active'), ('1', 'Paused'), ('2', 'In Progress'), ('2', 'Completed')], max_length=1)),
                ('due_date', models.DateField(default=None)),
                ('started_on', models.DateField(default=None)),
            ],
            options={
                'verbose_name_plural': 'modules',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='started_on',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('0', 'Active'), ('1', 'Paused'), ('2', 'In Progress'), ('2', 'Completed')], default=1, max_length=1)),
                ('due_date', models.DateField(default=None)),
                ('started_on', models.DateField(default=None)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.module')),
            ],
            options={
                'verbose_name_plural': 'modules',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.project'),
        ),
    ]
