# Generated by Django 4.1.1 on 2022-10-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_membership_timelog_team_membership_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPerson',
        ),
        migrations.CreateModel(
            name='MyTimeLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.timelog',),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='unit',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
